working on RACF for dbgmgr

diff --git a/eqae20/generate/007A_dbgmgr_startedtask b/eqae20/generate/007A_dbgmgr_startedtask
--- a/eqae20/generate/007A_dbgmgr_startedtask
+++ b/eqae20/generate/007A_dbgmgr_startedtask
@@ -42,7 +42,7 @@ startedTask="//*
 //*
 //* Debug Manager
 //*
-//DBGMGR   PROC PRM=,			* PRM=DEBUG TO START TRACING
+//DBGMGR   PROC PRM=,  * PRM=DEBUG TO START TRACING
 //	      LEPRM='RPTOPTS(ON)',
 //	      TZ='\${debug_tz}',
 //	      CLIENT=\${EQAE20_DBGMGR_CLIENT},
@@ -57,4 +57,14 @@ startedTask="//*
 //         PEND
 //*"
 
-echo "$startedTask"
+procregistrar eqae20 "${verb}" "dbgmgr" "\${startedTask}"
+exit \$?
+EOF
+
+if [ $? -gt 0 ]; then
+        echo "Unable to create EQAE20 Update script: ${script}." >&2
+        exit 16
+fi
+
+chmod u+x "${script}"
+exit 0
